export const countryCityMap: { [key: string]: string[] } = {
  Poland: [
    'Poznan',
    'Krakow',
    'Warsaw',
    'Wroclaw',
    'Gdansk',
    'Szczecin',
    'Katowice',
    'Lodz',
    'Bydgoszcz',
    'Lublin',
    'Bialystok',
    'Torun',
    'Czestochowa',
    'Rzeszow',
    'Kielce',
    'Gdynia',
    'Sosnowiec',
    'Radom',
    'Zielona Gora',
    'Tarnow',
    'Opole',
    'Olsztyn',
    'Bielsko-Biala',
    'Gorzow Wielkopolski',
    'Rybnik',
    'Walbrzych',
    'Plock',
    'Elblag',
    'Wałcz',
    'Tomaszow Mazowiecki',
  ],
  Germany: [
    'Berlin',
    'Munich',
    'Hamburg',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Dusseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Munster',
    'Karlsruhe',
    'Mannheim',
    'Augsburg',
    'Wiesbaden',
    'Mönchengladbach',
    'Gelsenkirchen',
    'Braunschweig',
    'Chemnitz',
    'Kiel',
    'Aachen',
  ],
  France: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Clermont-Ferrand',
    'Saint-Étienne',
    'Toulon',
    'Angers',
    'Grenoble',
    'Dijon',
    'Nîmes',
    'Villeurbanne',
    'Metz',
    'Brest',
    'Le Mans',
    'Amiens',
    'Perpignan',
    'Boulogne-Billancourt',
    'Besançon',
    'Orléans',
    'Mulhouse',
  ],
  'United Kingdom': [
    'London',
    'Manchester',
    'Birmingham',
    'Glasgow',
    'Liverpool',
    'Bristol',
    'Edinburgh',
    'Leeds',
    'Sheffield',
    'Newcastle',
    'Nottingham',
    'Cardiff',
    'Belfast',
    'Leicester',
    'Brighton',
    'Coventry',
    'Hull',
    'Stoke-on-Trent',
    'Wolverhampton',
    'Derby',
    'Plymouth',
    'Southampton',
    'Sunderland',
    'Portsmouth',
    'York',
    'Swansea',
    'Swindon',
    'Oxford',
    'Blackpool',
    'Middlesbrough',
  ],
  Italy: [
    'Rome',
    'Milan',
    'Venice',
    'Naples',
    'Turin',
    'Florence',
    'Bologna',
    'Genoa',
    'Bari',
    'Catania',
    'Palermo',
    'Padua',
    'Trieste',
    'Verona',
    'Cagliari',
    'Brescia',
    'Taranto',
    'Prato',
    'Reggio Calabria',
    'Modena',
    'Livorno',
    'Cosenza',
    'Pescara',
    'Parma',
    'Lecce',
    'Rimini',
    'Foggia',
    'Salerno',
    'Ferrara',
    'Sassari',
    'Latina',
  ],
  Spain: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Malaga',
    'Murcia',
    'Palma',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Cordoba',
    'Valladolid',
    'Vigo',
    'Gijon',
    'Hospitalet de Llobregat',
    'A Coruña',
    'Vitoria-Gasteiz',
    'Granada',
    'Elche',
    'Oviedo',
    'Badalona',
    'Cartagena',
    'Terrassa',
    'Jerez de la Frontera',
    'Sabadell',
    'Santa Cruz de Tenerife',
    'Mostoles',
    'Alcala de Henares',
  ],
  Portugal: [
    'Lisbon',
    'Porto',
    'Faro',
    'Coimbra',
    'Braga',
    'Aveiro',
    'Funchal',
    'Evora',
    'Setubal',
    'Viseu',
    'Viana do Castelo',
    'Portimao',
    'Guimaraes',
    'Braganca',
    'Faro',
    'Covilha',
    'Figueira da Foz',
    'Tomar',
    'Beja',
    'Vila Real',
    'Leiria',
    'Castelo Branco',
    'Guarda',
    'Penafiel',
    'Torres Vedras',
    'Barcelos',
    'Albufeira',
    'Mirandela',
    'Ponte de Lima',
    'Almada',
  ],
  Netherlands: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
    'Enschede',
    'Haarlem',
    'Arnhem',
    'Zaanstad',
    'Amersfoort',
    'Apeldoorn',
    's-Hertogenbosch',
    'Hoofddorp',
    'Maastricht',
    'Leiden',
    'Dordrecht',
    'Zoetermeer',
    'Zwolle',
    'Deventer',
    'Born',
    'Delft',
    'Leeuwarden',
    'Alkmaar',
    'Venlo',
    'Roosendaal',
  ],
  Belgium: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Bruges',
    'Liege',
    'Leuven',
    'Mechelen',
    'Aalst',
    'Kortrijk',
    'Hasselt',
    'Sint-Niklaas',
    'Ostend',
    'Tournai',
    'Genk',
    'Seraing',
    'Roeselare',
    'Mouscron',
    'Verviers',
    'Beveren',
    'Dendermonde',
    'Beringen',
    'Turnhout',
    'Dilbeek',
    'Heist-op-den-Berg',
    'Sint-Truiden',
    'Lokeren',
    "Braine-l'Alleud",
    'Herstal',
    'Ninove',
    'Geel',
  ],
  Switzerland: [
    'Zurich',
    'Geneva',
    'Bern',
    'Basel',
    'Lausanne',
    'Lucerne',
    'St. Gallen',
    'Lugano',
    'Biel',
    'Thun',
    'Köniz',
    'La Chaux-de-Fonds',
    'Fribourg',
    'Schaffhausen',
    'Chur',
    'Vernier',
    'Neuchatel',
    'Uster',
    'Sion',
    'Emmen',
    'Yverdon-les-Bains',
    'Lancy',
    'Zug',
    'Kriens',
    'Rapperswil-Jona',
    'Dübendorf',
    'Montreux',
    'Frauenfeld',
    'Dietikon',
    'Dubendorf',
  ],
  Sweden: [
    'Stockholm',
    'Gothenburg',
    'Malmo',
    'Uppsala',
    'Linkoping',
    'Helsingborg',
    'Jonkoping',
    'Norrkoping',
    'Lund',
    'Umea',
    'Gavle',
    'Boras',
    'Sodertalje',
    'Vasteras',
    'Orebro',
    'Huddinge',
    'Karlstad',
    'Taby',
    'Vaxjo',
    'Nacka',
    'Eskilstuna',
    'Halmstad',
    'Sollentuna',
    'Lulea',
    'Trollhattan',
    'Lidingo',
    'Bromma',
    'Karlskrona',
    'Uddevalla',
    'Skovde',
  ],
  Denmark: [
    'Copenhagen',
    'Aarhus',
    'Odense',
    'Aalborg',
    'Esbjerg',
    'Randers',
    'Kolding',
    'Vejle',
    'Horsens',
    'Roskilde',
    'Greve',
    'Hvidovre',
    'Herning',
    'Silkeborg',
    'Næstved',
    'Frederiksberg',
    'Viborg',
    'Køge',
    'Holstebro',
    'Taastrup',
    'Slagelse',
    'Hillerod',
    'Svendborg',
    'Holbaek',
    'Fredericia',
    'Hjorring',
    'Rodovre',
    'Helsingor',
    'Kolding',
    'Vejle',
  ],
  Norway: [
    'Oslo',
    'Bergen',
    'Trondheim',
    'Stavanger',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Tromso',
    'Sandnes',
    'Sarpsborg',
    'Skien',
    'Alesund',
    'Sandefjord',
    'Haugesund',
    'Tonsberg',
    'Moss',
    'Porsgrunn',
    'Bodo',
    'Arendal',
    'Hamar',
    'Ytrebygda',
    'Larvik',
    'Halden',
    'Steinkjer',
    'Harstad',
    'Lillehammer',
    'Molde',
    'Mo i Rana',
    'Kongsberg',
    'Askoy',
  ],
  Finland: [
    'Helsinki',
    'Espoo',
    'Tampere',
    'Vantaa',
    'Oulu',
    'Turku',
    'Jyvaskyla',
    'Lahti',
    'Kuopio',
    'Pori',
    'Kotka',
    'Joensuu',
    'Lappeenranta',
    'Hameenlinna',
    'Vaasa',
    'Seinajoki',
    'Rovaniemi',
    'Mikkeli',
    'Salo',
    'Porvoo',
    'Kokkola',
    'Lohja',
    'Hyvinkaa',
    'Jarvenpaa',
    'Rauma',
    'Kerava',
    'Kajaani',
    'Ylojarvi',
    'Hamina',
    'Lieto',
  ],
  'United States': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington',
    'Boston',
    'El Paso',
    'Detroit',
    'Nashville',
    'Portland',
    'Memphis',
    'Oklahoma City',
    'Las Vegas',
    'Louisville',
    'Baltimore',
  ],
  Canada: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Kitchener',
    'London',
    'Victoria',
    'Halifax',
    'Oshawa',
    'Windsor',
    'Saskatoon',
    'Regina',
    'Barrie',
    "St. John's",
    'Kelowna',
    'Sherbrooke',
    'Sudbury',
    'Kingston',
    'Thunder Bay',
    'Waterloo',
    'Saint John',
    'Brantford',
    'Moncton',
    'Nanaimo',
    'Red Deer',
  ],
  Australia: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Newcastle',
    'Canberra',
    'Sunshine Coast',
    'Wollongong',
    'Geelong',
    'Hobart',
    'Townsville',
    'Cairns',
    'Toowoomba',
    'Darwin',
    'Ballarat',
    'Bendigo',
    'Albury',
    'Launceston',
    'Mackay',
    'Rockhampton',
    'Bunbury',
    'Coffs Harbour',
    'Bundaberg',
    'Wagga Wagga',
    'Hervey Bay',
    'Mildura',
    'Shepparton',
    'Port Macquarie',
  ],
  Brazil: [
    'Sao Paulo',
    'Rio de Janeiro',
    'Salvador',
    'Brasilia',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Goiânia',
    'Belém',
    'Porto Alegre',
    'Campinas',
    'São Luís',
    'Natal',
    'João Pessoa',
    'Teresina',
    'Campo Grande',
    'São José dos Campos',
    'Cuiabá',
    'Aracaju',
    'Feira de Santana',
    'Londrina',
    'Juazeiro do Norte',
    'Joinville',
    'Bauru',
    'Anápolis',
    'Macaé',
    'Blumenau',
  ],
  China: [
    'Shanghai',
    'Beijing',
    'Guangzhou',
    'Shenzhen',
    'Wuhan',
    'Chengdu',
    'Chongqing',
    'Tianjin',
    'Hangzhou',
    'Nanjing',
    "Xi'an",
    'Shenyang',
    'Harbin',
    'Suzhou',
    'Dalian',
    'Qingdao',
    'Zhengzhou',
    'Shijiazhuang',
    'Jinan',
    'Changsha',
    'Kunming',
    'Changchun',
    'Nanchang',
    'Ürümqi',
    'Hefei',
    'Fuzhou',
    'Guiyang',
    'Nanning',
    'Haikou',
    'Xiamen',
  ],
  India: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Pimpri-Chinchwad',
    'Patna',
    'Vadodara',
    'Ghaziabad',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan-Dombivli',
    'Vasai-Virar',
    'Varanasi',
  ],
  Japan: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Kitakyushu',
    'Chiba',
    'Sakai',
    'Shizuoka',
    'Okayama',
    'Kumamoto',
    'Hamamatsu',
    'Hachiōji',
    'Sagamihara',
    'Funabashi',
    'Kagoshima',
    'Higashiosaka',
    'Himeji',
    'Utsunomiya',
    'Matsuyama',
    'Miyazaki',
    'Oita',
    'Kurashiki',
  ],
  'South Korea': [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Ulsan',
    'Suwon',
    'Changwon',
    'Seongnam',
    'Goyang',
    'Yongin',
    'Cheongju',
    'Jeonju',
    'Cheonan',
    'Asan',
    'Anyang',
    'Gimpo',
    'Jeju',
    'Pohang',
    'Ansan',
    'Wonju',
    'Uijeongbu',
    'Namyangju',
    'Hwaseong',
    'Suncheon',
    'Gumi',
    'Osan',
    'Iksan',
    'Gunpo',
  ],
  Russia: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Nizhny Novgorod',
    'Kazan',
    'Chelyabinsk',
    'Omsk',
    'Samara',
    'Rostov-on-Don',
    'Ufa',
    'Krasnoyarsk',
    'Voronezh',
    'Perm',
    'Volgograd',
    'Krasnodar',
    'Saratov',
    'Tyumen',
    'Tolyatti',
    'Izhevsk',
    'Barnaul',
    'Ulyanovsk',
    'Vladivostok',
    'Yaroslavl',
    'Irkutsk',
    'Khabarovsk',
  ],
  Mexico: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'Ciudad Juarez',
    'Leon',
    'Zapopan',
    'Naucalpan',
    'Merida',
    'San Luis Potosi',
    'Aguascalientes',
    'Hermosillo',
    'Saltillo',
    'Mexicali',
    'Culiacan',
    'Acapulco',
    'Tlalnepantla',
    'Cancun',
    'Queretaro',
    'Chihuahua',
    'Torreon',
    'Morelia',
    'Reynosa',
    'Tlaquepaque',
    'Tuxtla Gutierrez',
    'Durango',
    'Veracruz',
    'Irapuato',
  ],
  Argentina: [
    'Buenos Aires',
    'Cordoba',
    'Rosario',
    'Mendoza',
    'San Miguel de Tucuman',
    'La Plata',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
    'San Juan',
    'Resistencia',
    'Neuquen',
    'Corrientes',
    'Posadas',
    'Bahia Blanca',
    'Parana',
    'Formosa',
    'San Salvador de Jujuy',
    'Santiago del Estero',
    'Concordia',
    'San Nicolas de los Arroyos',
    'Rio Cuarto',
    'Comodoro Rivadavia',
    'San Rafael',
    'Trelew',
    'Pergamino',
    'San Fernando del Valle de Catamarca',
    'San Carlos de Bariloche',
  ],
  Iran: [
    'Tehran',
    'Mashhad',
    'Isfahan',
    'Karaj',
    'Tabriz',
    'Shiraz',
    'Qom',
    'Ahvaz',
    'Kermanshah',
    'Urmia',
    'Rasht',
    'Kerman',
    'Yazd',
    'Ardabil',
    'Bandar Abbas',
    'Zahedan',
    'Sari',
    'Khorramabad',
    'Arak',
    'Hamadan',
    'Qazvin',
    'Zanjan',
    'Sanandaj',
    'Qeshm',
    'Gorgan',
    'Birjand',
    'Abadan',
    'Ilam',
    'Bojnurd',
    'Kashan',
  ],
  Ukraine: [
    'Kyiv',
    'Kharkiv',
    'Odesa',
    'Dnipro',
    'Donetsk',
    'Zaporizhzhia',
    'Lviv',
    'Kryvyi Rih',
    'Mykolaiv',
    'Mariupol',
    'Luhansk',
    'Sevastopol',
    'Vinnytsia',
    'Makiivka',
    'Simferopol',
    'Kherson',
    'Chernihiv',
    'Poltava',
    'Cherkasy',
    'Zhytomyr',
    'Sumy',
    'Khmelnytskyi',
    'Rivne',
    'Kropyvnytskyi',
    'Ivano-Frankivsk',
    'Kamianske',
    'Ternopil',
    'Lutsk',
    'Kremenchuk',
    'Melitopol',
  ],
  Indonesia: [
    'Jakarta',
    'Surabaya',
    'Bandung',
    'Medan',
    'Bekasi',
    'Tangerang',
    'Depok',
    'Semarang',
    'Palembang',
    'Makassar',
    'South Tangerang',
    'Bandar Lampung',
    'Padang',
    'Denpasar',
    'Pontianak',
    'Balikpapan',
    'Cimahi',
    'Surakarta',
    'Banjarmasin',
    'Yogyakarta',
    'Manado',
    'Jambi',
    'Mataram',
    'Bogor',
    'Batam',
    'Padang',
    'Samarinda',
    'Pekanbaru',
    'Tasikmalaya',
    'Cirebon',
  ],
  Uzbekistan: [
    'Tashkent',
    'Namangan',
    'Samarkand',
    'Andijan',
    'Bukhara',
    'Nukus',
    'Qarshi',
    'Jizzakh',
    'Fergana',
    'Urgench',
    'Margilan',
    'Navoiy',
    'Chirchiq',
    'Tirmiz',
    'Kokand',
    'Angren',
    'Olmaliq',
    'Chust',
    'Denov',
    'Kogon',
    'Zomin',
    'Kattaqo’rg’on',
    'Chelak',
    'Chinoz',
    'Chortoq',
    'Dustlik',
    "G'ijduvon",
    "G'uzor",
    'Gagarin',
    'Gallaorol',
    'Guliston',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Tabuk',
    'Buraydah',
    'Khamis Mushait',
    "Ha'il",
    "Ta'if",
    'Najran',
    'Al-Qassim',
    'Al-Kharj',
    'Yanbu',
    'Abha',
    'Al-Hofuf',
    'Al-Mubarraz',
    'Hafar Al-Batin',
    'Arar',
    'Sakaka',
    'Jizan',
    'Dhahran',
    "Al-Majma'ah",
    'Al-Ula',
    'Unaizah',
    'Rafha',
    'Turaif',
    'Tarout Island',
    'Qurayyat',
    'Safwa',
    'Thuwal',
  ],
  Egypt: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra El-Kheima',
    'Port Said',
    'Suez',
    'Luxor',
    'El-Mahalla El-Kubra',
    'Tanta',
    'Asyut',
    'Ismailia',
    'Faiyum',
    'Zagazig',
    'Aswan',
    'Damietta',
    'Damanhur',
    'El-Mansoura',
    'Beni Suef',
    'Hurghada',
    'Akhmim',
    'Mallawi',
    'Kafr el-Sheikh',
    'Siwa Oasis',
    'Jirja',
    'Marsa Matruh',
    'Al-Minya',
    'Qena',
    'Sohag',
    'Edfu',
    'Sharm El Sheikh',
  ],
  Philippines: [
    'Quezon City',
    'Manila',
    'Caloocan',
    'Davao City',
    'Cebu City',
    'Zamboanga City',
    'Taguig',
    'Pasig',
    'Valenzuela',
    'Las Piñas',
    'Antipolo',
    'Makati',
    'Marikina',
    'Navotas',
    'Cagayan de Oro',
    'Parañaque',
    'Pasay',
    'General Santos',
    'Muntinlupa',
    'Iloilo City',
    'San Jose del Monte',
    'Bacoor',
    'Calamba',
    'Cainta',
    'Bacolod',
    'Angeles',
    'Mabalacat',
    'Dasmariñas',
    'Santa Rosa',
    'Baguio',
  ],
  Malaysia: [
    'Kuala Lumpur',
    'George Town',
    'Ipoh',
    'Shah Alam',
    'Petaling Jaya',
    'Johor Bahru',
    'Kuching',
    'Kota Kinabalu',
    'Sandakan',
    'Seremban',
    'Kuantan',
    'Tawau',
    'Kuala Terengganu',
    'Miri',
    'Alor Setar',
    'Kota Bharu',
    'Sungai Petani',
    'Bukit Mertajam',
    'Taiping',
    'Kulim',
    'Sibu',
    'Melaka',
    'Kuala Langat',
    'Temerloh',
    'Tampin',
    'Kangar',
    'Kubang Pasu',
    'Papar',
    'Bintulu',
    'Pasir Mas',
  ],
  Iraq: [
    'Baghdad',
    'Basra',
    'Sulaymaniyah',
    'Erbil',
    'Kirkuk',
    'Najaf',
    'Karbala',
    'Nasiriyah',
    'Dhi Qar',
    'Anbar',
    'Wasit',
    'Maysan',
    'Diyala',
    'Saladin',
    'Kadhimain',
    'Balad',
    'Tikrit',
    'Kirkuk',
    'Rutba',
    'Mosul',
    'Sinjar',
    'Tel Afar',
    'Dohuk',
    'Zakho',
    'Shingal',
    'Al-Qosh',
    'Halabja',
    'Khanaqin',
    'Tuz Khurmatu',
    'Kifri',
    'Akashat',
  ],
  Turkey: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Adana',
    'Gaziantep',
    'Konya',
    'Antalya',
    'Mersin',
    'Kayseri',
    'Diyarbakır',
    'Samsun',
    'Denizli',
    'Şanlıurfa',
    'Adapazarı',
    'Malatya',
    'Kahramanmaraş',
    'Erzurum',
    'Van',
    'Batman',
    'Elazığ',
    'Manisa',
    'Sivas',
    'Gebze',
    'Balıkesir',
    'Tarsus',
    'Kütahya',
    'Trabzon',
    'Çorum',
    'Şırnak',
    'Kırıkkale',
  ],
  Thailand: [
    'Bangkok',
    'Nonthaburi',
    'Nakhon Ratchasima',
    'Chiang Mai',
    'Hat Yai',
    'Udon Thani',
    'Pak Kret',
    'Khon Kaen',
    'Chaophraya Surasak',
    'Ubon Ratchathani',
    'Nakhon Si Thammarat',
    'Nakhon Sawan',
    'Nakhon Pathom',
    'Phitsanulok',
    'Chiang Rai',
    'Samut Prakan',
    'Phuket',
    'Mueang Nonthaburi',
    'Hatyai',
    'Nakhon Si Thammarat',
    'Ubon Ratchathani',
    'Surat Thani',
    'Khon Kaen',
    'Udon Thani',
    'Pathum Thani',
    'Rayong',
    'Samut Prakan',
    'Ayutthaya',
    'Chon Buri',
    'Nakhon Sawan',
  ],
};
